### ISSUE TITLE
Cutomize Serial object

### ISSUE THREAD

**Issue by Kenuat** [MrYsLab/pymata-aio#43]
Hi, while investigating my problem from https://github.com/MrYsLab/pymata-aio/issues/42, I've found that my USB-TTL converter requires _rtsState field of the Serial object to be set to 0 (by default it equals 1). This is done via Serial.setRTS(0) method.
To make this work in pymata I had to override start_aio method to only add single `self.serial_port.my_serial.setRTS(0)` string after PymataSerial object initialization.
Could you please suggest more elegant way to make such change? Maybe it is possible to init PymataSerial with my own pyserial object?
Thanks in advance.

**Comment by MrYsLab** [comment]
@Kenuat I am glad you found the problem. Maintaining your own custom copy of pymata_serial is probably best for now, since this is a very special case for the APC220. Since I do not own an APC220, I am reluctant to add changes that I cannot test across several scenarios and with different types of Arduino boards.  Thanks for letting me know about your success.
