### ISSUE TITLE
Is WeMos / Esp8266 boards supported?

### ISSUE THREAD

**Issue by hyansuper** [MrYsLab/pymata-aio#98]
Hello,
I got a WeMos D1 board, it has a Esp8266 chip, so it would be more convenient with wifi and without usb line.
In the arduino IDE, I set Tool > Boards > "WeMo D1 R1" or "Esp8266 generic device" and compile the FirmataPlus.ino, the error output:
```
Build options changed, rebuilding all
Multiple libraries were found for "Servo.h"
In file included from /tmp/arduino_modified_sketch_995868/FirmataPlus.ino:46:0:
 Used: /home/hyan/.arduino15/packages/esp8266/hardware/esp8266/2.5.2/libraries/Servo
/home/hyan/Arduino/libraries/NewPing/NewPing.h:113:20: fatal error: avr/io.h: No such file or directory
 Not used: /home/hyan/Arduino/libraries/Servo
 #include <avr/io.h>

                    ^
compilation terminated.
 Not used: /home/hyan/arduino-1.8.9/libraries/Servo
exit status 1
Error compiling for board Generic ESP8266 Module.

```
Is my board supported?
I see [here](https://github.com/MrYsLab/pymata-aio/blob/master/FirmataPlus/source/libraries/Firmata/Boards.h#L686) in the board.h seems to support Esp8266.

If I select Nano board, I compiles with no error.

**Comment by MrYsLab** [comment]
I installed the 8266 libraries [using the instructions in this guide](https://arduino-esp8266.readthedocs.io/en/2.5.2/installing.html) and StandardFirmata compiles. FirmataPlus does not compile because it assumes the board is using an AVR processor.

I have never tried using the ESP8266 with Firmata. Instead, I am using [Python Banyan](https://mryslab.github.io/python_banyan/). 

There is a[ demo for the ESP8266 with a GUI interface ](https://mryslab.github.io/python_banyan/#one_gpio_demos/#running-the-web-demo-station-for-the-esp-8266)to drive the demo. The demo communicates with the ESP8266 over WiFi.
